### ISSUE TITLE
Battery percentages overlay

### ISSUE THREAD

**Issue by igobythisname** [asterixgaul/digitalbattery13lite#1]
![BB6CD964-899B-4E2E-B99B-3A8C7B274703](https://user-images.githubusercontent.com/25451059/82962485-36f16080-9f75-11ea-9211-a5b61cef6b95.jpeg)
![8482A2CC-7B45-4EE5-844C-EDC9ED227EC5](https://user-images.githubusercontent.com/25451059/82962488-3953ba80-9f75-11ea-9dc8-d3be3e522e90.png)
![D593BE33-9B7E-48B3-B25A-E3C4F90BE926](https://user-images.githubusercontent.com/25451059/82962495-3ce74180-9f75-11ea-9ae2-e26cf4a12a80.jpeg)

I woke up this morning and looking at my battery was confusing, text not clear; seems the battery percentage when I started charging gets frozen below and 100 overlays; used my phone til 39% then plugged in, unplugged from charge after it reached 100% and now the same thing is happening. A respring does resolve the bug.

**Comment by asterixgaul** [comment]
I will upload beta 6 to the github, please report back if the issue is still present on beta 6

On 27 May 2020, at 10:24 am, igobythisname <notifications@github.com> wrote:

﻿

[BB6CD964-899B-4E2E-B99B-3A8C7B274703]<https://user-images.githubusercontent.com/25451059/82962485-36f16080-9f75-11ea-9211-a5b61cef6b95.jpeg>
[8482A2CC-7B45-4EE5-844C-EDC9ED227EC5]<https://user-images.githubusercontent.com/25451059/82962488-3953ba80-9f75-11ea-9dc8-d3be3e522e90.png>
[D593BE33-9B7E-48B3-B25A-E3C4F90BE926]<https://user-images.githubusercontent.com/25451059/82962495-3ce74180-9f75-11ea-9ae2-e26cf4a12a80.jpeg>

I woke up this morning and looking at my battery was confusing, text not clear; seems the battery percentage when I started charging gets frozen below and 100 overlays; used my phone til 39% then plugged in, unplugged from charge after it reached 100% and now the same thing is happening. A respring does resolve the bug.

**Comment by igobythisname** [comment]
Awesome, you ROCK! Thanks!! :D

**Comment by igobythisname** [comment]
> I will upload beta 6 to the github, please report back if the issue is still present on beta 6

charged overnight, woke up this morning and no overlay bug. You ROCK! AWESOME!! THANK YOU!!!
